version: "3.9"
services:
  rabbitmq-message-app:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # RabbitMQ server
      - "15672:15672" # Management console
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
  mongo-message-app:
    image: mongo:latest
    restart: "no"
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
