### GET MESSAGE SSE client 1
// @no-log
GET localhost:8081/api/v1/message
Accept: application/x-ndjson
User-uuid: {{user1id}}

### POST MESSAGE client 1
// @no-log
POST localhost:8081/api/v1/message
Content-Type: application/json
User-uuid: {{user1id}}

{
  "destinationChanelUuid": "{{channel1id}}",
  "messageContent": "T1231312313213123131est"
}

### GET MESSAGE SSE client 2
// @no-log
GET localhost:8081/api/v1/message
Accept: application/x-ndjson
User-uuid: {{user2id}}

### POST MESSAGE  client 2
// @no-log
POST localhost:8081/api/v1/message
Content-Type: application/json
User-uuid: {{user2id}}

{
  "destinationChanelUuid": "{{channel1id}}",
  "messageContent": "111"
}
