### GET MESSAGE SSE client 1
GET localhost:8081/api/v1/message
Accept: application/x-ndjson
User-uuid: 594cecd5-1921-417a-98bd-173262f651ff

### GET MESSAGE SSE client 2
GET localhost:8081/api/v1/message
Accept: application/x-ndjson
User-uuid: fe1137a0-6736-4868-ad58-aefcdf800509

### POST MESSAGE client 1
POST localhost:8081/api/v1/message
Content-Type: application/json
User-uuid: 594cecd5-1921-417a-98bd-173262f651ff

{
  "destinationChanelUuid": "633997755f9fa078bc06aba5",
  "messageContent": "T1231312313213123131est"
}

### POST MESSAGE  client 2
POST localhost:8081/api/v1/message
Content-Type: application/json
User-uuid: fe1137a0-6736-4868-ad58-aefcdf800509

{
  "destinationChanelUuid": "633997755f9fa078bc06aba6",
  "messageContent": "123"
}